"""Train Model 1 — Triage CatBoost classifier.

Run:
    python train.py

Inputs:
    data/triage_synthetic.csv  (generated by data_generation.py)

Outputs:
    artifacts/model.cbm
    artifacts/features.json
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd
from catboost import CatBoostClassifier, Pool
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split

from data_generation import CATEGORY_ORDER, CHIEF_COMPLAINTS

DATASET_PATH = Path(__file__).parent / "data" / "triage_synthetic.csv"
ARTIFACTS_DIR = Path(__file__).parent / "artifacts"

FEATURE_COLS = [
    "heart_rate",
    "systolic_bp",
    "diastolic_bp",
    "temperature",
    "respiratory_rate",
    "spo2",
    "pain_scale",
    "age",
    "chief_complaint_code",
    "shock_index",
]
TARGET_COL = "triage_label"

LABEL_TO_INT = {label: i for i, label in enumerate(CATEGORY_ORDER)}
INT_TO_LABEL = {i: label for i, label in enumerate(CATEGORY_ORDER)}


def train() -> None:
    if not DATASET_PATH.exists():
        raise FileNotFoundError(
            f"Training data not found: {DATASET_PATH}\n"
            "Run:  python data_generation.py"
        )

    df = pd.read_csv(DATASET_PATH)
    print(f"Loaded {len(df)} rows. Label distribution:")
    print(df[TARGET_COL].value_counts().to_string(), "\n")

    X = df[FEATURE_COLS].astype(float).values
    y = df[TARGET_COL].map(LABEL_TO_INT).values

    # Medians from training data (used for missing-value imputation at inference)
    medians: dict[str, float] = {
        col: float(np.median(df[col].astype(float).values))
        for col in FEATURE_COLS
    }

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    model = CatBoostClassifier(
        iterations=400,
        depth=7,
        learning_rate=0.08,
        loss_function="MultiClass",
        classes_count=4,
        auto_class_weights="Balanced",
        eval_metric="Accuracy",
        random_seed=42,
        verbose=50,
    )

    train_pool = Pool(X_train, y_train, feature_names=FEATURE_COLS)
    eval_pool  = Pool(X_test,  y_test,  feature_names=FEATURE_COLS)
    model.fit(train_pool, eval_set=eval_pool)

    y_pred = model.predict(X_test).flatten().astype(int)
    overall_acc = accuracy_score(y_test, y_pred)
    print(f"\nOverall accuracy: {overall_acc:.4f}")

    print("\nPer-class report:")
    print(classification_report(y_test, y_pred, target_names=CATEGORY_ORDER))

    print("Confusion matrix (rows=actual, cols=predicted):")
    cm = confusion_matrix(y_test, y_pred)
    cm_df = pd.DataFrame(cm, index=CATEGORY_ORDER, columns=CATEGORY_ORDER)
    print(cm_df.to_string(), "\n")

    ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)
    model_path = ARTIFACTS_DIR / "model.cbm"
    model.save_model(str(model_path))
    print(f"Model saved → {model_path}")

    features_meta = {
        "feature_cols": FEATURE_COLS,
        "medians": medians,
        "category_order": CATEGORY_ORDER,
        "label_to_int": LABEL_TO_INT,
        "chief_complaints": CHIEF_COMPLAINTS,
        "overall_accuracy": round(overall_acc, 4),
    }
    features_path = ARTIFACTS_DIR / "features.json"
    with open(features_path, "w") as f:
        json.dump(features_meta, f, indent=2)
    print(f"Features meta saved → {features_path}")

    if overall_acc < 0.75:
        print(f"\nWARNING: accuracy {overall_acc:.4f} is below 0.75 threshold.")
    else:
        print(f"\nPASS: accuracy {overall_acc:.4f} ≥ 0.75")


if __name__ == "__main__":
    train()
