"""Train Model 1 — Triage classifier.

Run:
    python train.py

Inputs:
    dataset/triage_train.csv  (generated by data_generation.py)

Outputs:
    artifacts/triage_model.pkl
    artifacts/triage_label_encoder.pkl
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report
import xgboost as xgb
import shap
import joblib

DATASET_PATH = Path(__file__).parent / "dataset" / "triage_train.csv"
ARTIFACTS_DIR = Path(__file__).parent / "artifacts"

FEATURE_COLS = [
    "resp_rate",
    "spo2",
    "supplemental_o2",
    "temp",
    "systolic_bp",
    "heart_rate",
    "avpu",
]
TARGET_COL = "triage_category"


def train() -> None:
    if not DATASET_PATH.exists():
        raise FileNotFoundError(
            f"Training data not found at {DATASET_PATH}. "
            "Run data_generation.py first."
        )

    df = pd.read_csv(DATASET_PATH)
    df["supplemental_o2"] = df["supplemental_o2"].astype(int)

    X = df[FEATURE_COLS].values
    le = LabelEncoder()
    y = le.fit_transform(df[TARGET_COL])

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    model = xgb.XGBClassifier(
        n_estimators=200,
        max_depth=6,
        learning_rate=0.1,
        use_label_encoder=False,
        eval_metric="mlogloss",
        random_state=42,
    )
    model.fit(X_train, y_train, eval_set=[(X_test, y_test)], verbose=False)

    y_pred = model.predict(X_test)
    print(classification_report(y_test, y_pred, target_names=le.classes_))

    # SHAP explanation on a small sample
    explainer = shap.TreeExplainer(model)
    sample = X_test[:100]
    shap_values = explainer.shap_values(sample)
    print(f"SHAP computed for {len(sample)} samples, shape: {np.array(shap_values).shape}")

    ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)
    joblib.dump(model, ARTIFACTS_DIR / "triage_model.pkl")
    joblib.dump(le, ARTIFACTS_DIR / "triage_label_encoder.pkl")
    print(f"Artifacts saved → {ARTIFACTS_DIR}")


if __name__ == "__main__":
    train()
