"""Static clinical reference ranges for Model 3 — Lab Report Parser.

Rules-based lookup table: no ML training involved. Ranges are standard
textbook adult reference intervals; critical/panic thresholds follow
commonly cited hospital laboratory critical-value lists and vary by
institution in real practice.

Each entry:
{
    "display_name": "Hemoglobin",
    "aliases": ["hb", "haemoglobin", "hgb"],
    "unit": "g/dL",
    "male_low": 13.0, "male_high": 17.5,
    "female_low": 12.0, "female_high": 15.5,
    "critical_low": 8.0, "critical_high": 20.0,
    "category": "CBC",
    "plain_low": "low hemoglobin, which can cause fatigue and breathlessness",
    "plain_high": "high hemoglobin",
    "clinical_low": "Anemia — consider iron studies, reticulocyte count, B12, folate",
    "clinical_high": "Polycythemia — assess hydration status and secondary causes",
}
"""
from __future__ import annotations

from typing import Optional

REFERENCE_RANGES: dict[str, dict] = {
    # ---------------------------------------------------------------- CBC --
    "hemoglobin": {
        "display_name": "Hemoglobin", "category": "CBC", "unit": "g/dL",
        "aliases": ["hb", "haemoglobin", "hgb"],
        "male_low": 13.0, "male_high": 17.5, "female_low": 12.0, "female_high": 15.5,
        "critical_low": 8.0, "critical_high": 20.0,
        "plain_low": "low hemoglobin, which can cause fatigue and breathlessness",
        "plain_high": "high hemoglobin, which can thicken the blood",
        "clinical_low": "Anemia — consider iron studies, reticulocyte count, B12, folate",
        "clinical_high": "Polycythemia — assess hydration status and secondary causes",
    },
    "wbc": {
        "display_name": "WBC", "category": "CBC", "unit": "10^3/uL",
        "aliases": ["wbc", "white blood cell count", "total leukocyte count", "tlc", "leukocyte count"],
        "male_low": 4.0, "male_high": 11.0, "female_low": 4.0, "female_high": 11.0,
        "critical_low": 2.0, "critical_high": 30.0,
        "plain_low": "a low white blood cell count, which can affect your ability to fight infection",
        "plain_high": "a high white blood cell count, often a sign your body is fighting an infection",
        "clinical_low": "Leukopenia — consider bone marrow suppression, viral infection, sepsis",
        "clinical_high": "Leukocytosis — consider infection, inflammation, or leukemoid reaction",
    },
    "platelets": {
        "display_name": "Platelets", "category": "CBC", "unit": "10^3/uL",
        "aliases": ["plt", "platelet count"],
        "male_low": 150, "male_high": 400, "female_low": 150, "female_high": 400,
        "critical_low": 50, "critical_high": 1000,
        "plain_low": "a low platelet count, which can increase bleeding risk",
        "plain_high": "a high platelet count, which can increase clotting risk",
        "clinical_low": "Thrombocytopenia — consider ITP, DIC, marrow suppression, splenic sequestration",
        "clinical_high": "Thrombocytosis — consider reactive causes or myeloproliferative disorder",
    },
    "rbc": {
        "display_name": "RBC", "category": "CBC", "unit": "million/uL",
        "aliases": ["red blood cell count", "erythrocyte count"],
        "male_low": 4.5, "male_high": 5.9, "female_low": 4.0, "female_high": 5.2,
        "critical_low": 2.0, "critical_high": 7.5,
        "plain_low": "a low red blood cell count",
        "plain_high": "a high red blood cell count",
        "clinical_low": "Anemia — correlate with hemoglobin and hematocrit",
        "clinical_high": "Erythrocytosis — assess hydration and secondary causes",
    },
    "hematocrit": {
        "display_name": "Hematocrit", "category": "CBC", "unit": "%",
        "aliases": ["hct", "pcv", "packed cell volume"],
        "male_low": 38.8, "male_high": 50.0, "female_low": 34.9, "female_high": 44.5,
        "critical_low": 18.0, "critical_high": 60.0,
        "plain_low": "a low proportion of red blood cells in your blood",
        "plain_high": "a high proportion of red blood cells in your blood",
        "clinical_low": "Anemia — correlate with hemoglobin and RBC indices",
        "clinical_high": "Hemoconcentration or polycythemia — assess volume status",
    },
    "neutrophils": {
        "display_name": "Neutrophils", "category": "CBC", "unit": "%",
        "aliases": ["neutrophil count", "polymorphs", "polys"],
        "male_low": 40.0, "male_high": 75.0, "female_low": 40.0, "female_high": 75.0,
        "critical_low": 10.0, "critical_high": 95.0,
        "plain_low": "a low count of one type of infection-fighting white cell",
        "plain_high": "a high count of one type of infection-fighting white cell",
        "clinical_low": "Neutropenia — assess infection risk, consider marrow causes",
        "clinical_high": "Neutrophilia — consider acute bacterial infection or inflammation",
    },
    "lymphocytes": {
        "display_name": "Lymphocytes", "category": "CBC", "unit": "%",
        "aliases": ["lymphocyte count", "lymphs"],
        "male_low": 20.0, "male_high": 45.0, "female_low": 20.0, "female_high": 45.0,
        "critical_low": 5.0, "critical_high": 90.0,
        "plain_low": "a low count of another type of infection-fighting white cell",
        "plain_high": "a high count of another type of infection-fighting white cell",
        "clinical_low": "Lymphopenia — consider viral illness, immunosuppression",
        "clinical_high": "Lymphocytosis — consider viral infection or lymphoproliferative disorder",
    },
    "mcv": {
        "display_name": "MCV", "category": "CBC", "unit": "fL",
        "aliases": ["mean corpuscular volume"],
        "male_low": 80.0, "male_high": 100.0, "female_low": 80.0, "female_high": 100.0,
        "critical_low": 60.0, "critical_high": 120.0,
        "plain_low": "smaller than average red blood cells",
        "plain_high": "larger than average red blood cells",
        "clinical_low": "Microcytosis — consider iron deficiency or thalassemia",
        "clinical_high": "Macrocytosis — consider B12/folate deficiency, alcohol use, or hypothyroidism",
    },
    "mch": {
        "display_name": "MCH", "category": "CBC", "unit": "pg",
        "aliases": ["mean corpuscular hemoglobin"],
        "male_low": 27.0, "male_high": 33.0, "female_low": 27.0, "female_high": 33.0,
        "critical_low": 20.0, "critical_high": 40.0,
        "plain_low": "lower than average hemoglobin content per red blood cell",
        "plain_high": "higher than average hemoglobin content per red blood cell",
        "clinical_low": "Hypochromia — consider iron deficiency",
        "clinical_high": "Correlate with MCV; consider macrocytic process",
    },
    # ---------------------------------------------------------------- LFT --
    "alt": {
        "display_name": "ALT", "category": "LFT", "unit": "U/L",
        "aliases": ["sgpt", "alanine aminotransferase", "alanine transaminase"],
        "male_low": 7, "male_high": 55, "female_low": 7, "female_high": 45,
        "critical_low": 0, "critical_high": 500,
        "plain_low": "a low liver enzyme level (usually not a concern)",
        "plain_high": "a high liver enzyme level, which can indicate liver stress or damage",
        "clinical_low": "Not clinically significant in isolation",
        "clinical_high": "Hepatocellular injury — consider viral hepatitis, drug toxicity, fatty liver disease",
    },
    "ast": {
        "display_name": "AST", "category": "LFT", "unit": "U/L",
        "aliases": ["sgot", "aspartate aminotransferase", "aspartate transaminase"],
        "male_low": 8, "male_high": 48, "female_low": 8, "female_high": 43,
        "critical_low": 0, "critical_high": 500,
        "plain_low": "a low liver enzyme level (usually not a concern)",
        "plain_high": "a high liver enzyme level, which can indicate liver or muscle stress",
        "clinical_low": "Not clinically significant in isolation",
        "clinical_high": "Consider hepatocellular injury, muscle injury, or cardiac cause; correlate with ALT",
    },
    "alp": {
        "display_name": "ALP", "category": "LFT", "unit": "U/L",
        "aliases": ["alkaline phosphatase", "alk phos", "alk. phosphatase"],
        "male_low": 44, "male_high": 147, "female_low": 44, "female_high": 147,
        "critical_low": 20, "critical_high": 1000,
        "plain_low": "a low level of an enzyme related to liver and bone health",
        "plain_high": "a high level of an enzyme related to liver and bone health",
        "clinical_low": "Consider malnutrition, hypothyroidism, or Wilson disease",
        "clinical_high": "Consider cholestasis, biliary obstruction, or bone disease",
    },
    "total_bilirubin": {
        "display_name": "Total Bilirubin", "category": "LFT", "unit": "mg/dL",
        "aliases": ["bilirubin", "total bilirubin", "t.bilirubin", "tbil", "bilirubin total"],
        "male_low": 0.2, "male_high": 1.2, "female_low": 0.2, "female_high": 1.2,
        "critical_low": 0.0, "critical_high": 15.0,
        "plain_low": "a low bilirubin level (not typically a concern)",
        "plain_high": "high bilirubin, which can cause yellowing of the skin or eyes",
        "clinical_low": "Not clinically significant in isolation",
        "clinical_high": "Hyperbilirubinemia — evaluate for hemolysis, hepatocellular, or obstructive cause",
    },
    "direct_bilirubin": {
        "display_name": "Direct Bilirubin", "category": "LFT", "unit": "mg/dL",
        "aliases": ["direct bilirubin", "d.bilirubin", "dbil", "conjugated bilirubin"],
        "male_low": 0.0, "male_high": 0.3, "female_low": 0.0, "female_high": 0.3,
        "critical_low": 0.0, "critical_high": 5.0,
        "plain_low": "a normal-to-low conjugated bilirubin level",
        "plain_high": "high conjugated bilirubin, suggesting a bile flow problem",
        "clinical_low": "Not clinically significant in isolation",
        "clinical_high": "Suggests cholestatic or obstructive process; consider imaging of biliary tree",
    },
    "albumin": {
        "display_name": "Albumin", "category": "LFT", "unit": "g/dL",
        "aliases": ["alb", "serum albumin"],
        "male_low": 3.5, "male_high": 5.0, "female_low": 3.5, "female_high": 5.0,
        "critical_low": 1.5, "critical_high": 6.0,
        "plain_low": "low protein levels, which can indicate poor nutrition or liver/kidney issues",
        "plain_high": "high protein levels, often related to dehydration",
        "clinical_low": "Hypoalbuminemia — consider malnutrition, liver disease, nephrotic syndrome, inflammation",
        "clinical_high": "Usually reflects hemoconcentration/dehydration",
    },
    "total_protein": {
        "display_name": "Total Protein", "category": "LFT", "unit": "g/dL",
        "aliases": ["tp", "serum total protein"],
        "male_low": 6.0, "male_high": 8.3, "female_low": 6.0, "female_high": 8.3,
        "critical_low": 3.0, "critical_high": 12.0,
        "plain_low": "low total protein in your blood",
        "plain_high": "high total protein in your blood",
        "clinical_low": "Consider malnutrition, liver disease, or protein-losing states",
        "clinical_high": "Consider dehydration, chronic inflammation, or paraproteinemia",
    },
    "ggt": {
        "display_name": "GGT", "category": "LFT", "unit": "U/L",
        "aliases": ["gamma gt", "gamma-glutamyl transferase", "ggtp"],
        "male_low": 8, "male_high": 61, "female_low": 5, "female_high": 36,
        "critical_low": 0, "critical_high": 500,
        "plain_low": "a low liver enzyme level (usually not a concern)",
        "plain_high": "a high liver enzyme level, often linked to bile duct or alcohol-related stress",
        "clinical_low": "Not clinically significant in isolation",
        "clinical_high": "Consider cholestasis, alcohol use, or hepatobiliary disease",
    },
    # ---------------------------------------------------------------- KFT --
    "creatinine": {
        "display_name": "Creatinine", "category": "KFT", "unit": "mg/dL",
        "aliases": ["creat", "s.creatinine", "serum creatinine"],
        "male_low": 0.7, "male_high": 1.3, "female_low": 0.6, "female_high": 1.1,
        "critical_low": 0.0, "critical_high": 6.0,
        "plain_low": "a low kidney function marker (usually not a concern)",
        "plain_high": "a high kidney function marker, which can indicate reduced kidney function",
        "clinical_low": "Not clinically significant in isolation",
        "clinical_high": "Suggests reduced renal function — assess for acute kidney injury or CKD",
    },
    "bun": {
        "display_name": "BUN", "category": "KFT", "unit": "mg/dL",
        "aliases": ["blood urea nitrogen"],
        "male_low": 7, "male_high": 20, "female_low": 7, "female_high": 20,
        "critical_low": 2, "critical_high": 100,
        "plain_low": "a low waste-product marker, often related to diet or liver function",
        "plain_high": "a high waste-product marker, which can indicate kidney or dehydration issues",
        "clinical_low": "Consider malnutrition or liver disease",
        "clinical_high": "Consider renal impairment, dehydration, or GI bleeding",
    },
    "urea": {
        "display_name": "Urea", "category": "KFT", "unit": "mg/dL",
        "aliases": ["s.urea", "serum urea", "blood urea"],
        "male_low": 15, "male_high": 45, "female_low": 15, "female_high": 45,
        "critical_low": 5, "critical_high": 200,
        "plain_low": "a low waste-product marker, often related to diet or liver function",
        "plain_high": "a high waste-product marker, which can indicate kidney or dehydration issues",
        "clinical_low": "Consider malnutrition or liver disease",
        "clinical_high": "Consider renal impairment, dehydration, or GI bleeding",
    },
    "egfr": {
        "display_name": "eGFR", "category": "KFT", "unit": "mL/min/1.73m2",
        "aliases": ["gfr", "estimated glomerular filtration rate"],
        "male_low": 90, "male_high": 200, "female_low": 90, "female_high": 200,
        "critical_low": 15, "critical_high": 200,
        "plain_low": "reduced kidney filtering ability",
        "plain_high": "an above-expected filtering estimate",
        "clinical_low": "Reduced renal function — stage per KDIGO criteria and trend serially",
        "clinical_high": "Not clinically significant",
    },
    "uric_acid": {
        "display_name": "Uric Acid", "category": "KFT", "unit": "mg/dL",
        "aliases": ["s.uric acid", "serum uric acid"],
        "male_low": 3.4, "male_high": 7.0, "female_low": 2.4, "female_high": 6.0,
        "critical_low": 1.0, "critical_high": 12.0,
        "plain_low": "a low uric acid level (usually not a concern)",
        "plain_high": "a high uric acid level, which can be linked to gout",
        "clinical_low": "Not clinically significant in isolation",
        "clinical_high": "Hyperuricemia — consider gout risk, tumor lysis, or renal impairment",
    },
    "sodium": {
        "display_name": "Sodium", "category": "KFT", "unit": "mEq/L",
        "aliases": ["na", "na+", "s.sodium", "serum sodium"],
        "male_low": 136, "male_high": 145, "female_low": 136, "female_high": 145,
        "critical_low": 120, "critical_high": 160,
        "plain_low": "low blood sodium, which can cause confusion or weakness",
        "plain_high": "high blood sodium, often related to dehydration",
        "clinical_low": "Hyponatremia — assess volume status and osmolality",
        "clinical_high": "Hypernatremia — assess free water deficit",
    },
    "potassium": {
        "display_name": "Potassium", "category": "KFT", "unit": "mEq/L",
        "aliases": ["k", "k+", "s.potassium", "serum potassium"],
        "male_low": 3.5, "male_high": 5.0, "female_low": 3.5, "female_high": 5.0,
        "critical_low": 2.5, "critical_high": 6.5,
        "plain_low": "low blood potassium, which can affect heart rhythm",
        "plain_high": "high blood potassium, which can affect heart rhythm",
        "clinical_low": "Hypokalemia — cardiac monitoring advised, correct with caution",
        "clinical_high": "Hyperkalemia — urgent cardiac monitoring and correction advised",
    },
    "chloride": {
        "display_name": "Chloride", "category": "KFT", "unit": "mEq/L",
        "aliases": ["cl", "cl-", "s.chloride", "serum chloride"],
        "male_low": 98, "male_high": 107, "female_low": 98, "female_high": 107,
        "critical_low": 80, "critical_high": 120,
        "plain_low": "a low chloride level",
        "plain_high": "a high chloride level",
        "clinical_low": "Consider vomiting, diuretic use, or metabolic alkalosis",
        "clinical_high": "Consider dehydration or metabolic acidosis",
    },
    # ------------------------------------------------------------ Thyroid --
    "tsh": {
        "display_name": "TSH", "category": "Thyroid", "unit": "uIU/mL",
        "aliases": ["thyroid stimulating hormone", "thyrotropin"],
        "male_low": 0.4, "male_high": 4.0, "female_low": 0.4, "female_high": 4.0,
        "critical_low": 0.01, "critical_high": 100.0,
        "plain_low": "a low thyroid-stimulating hormone level, often seen with an overactive thyroid",
        "plain_high": "a high thyroid-stimulating hormone level, often seen with an underactive thyroid",
        "clinical_low": "Suggests hyperthyroidism — confirm with free T3/T4",
        "clinical_high": "Suggests hypothyroidism — confirm with free T4",
    },
    "free_t3": {
        "display_name": "Free T3", "category": "Thyroid", "unit": "pg/mL",
        "aliases": ["ft3", "free triiodothyronine"],
        "male_low": 2.3, "male_high": 4.2, "female_low": 2.3, "female_high": 4.2,
        "critical_low": 1.0, "critical_high": 10.0,
        "plain_low": "a low active thyroid hormone level",
        "plain_high": "a high active thyroid hormone level",
        "clinical_low": "Consider hypothyroidism or non-thyroidal illness",
        "clinical_high": "Consider thyrotoxicosis",
    },
    "free_t4": {
        "display_name": "Free T4", "category": "Thyroid", "unit": "ng/dL",
        "aliases": ["ft4", "free thyroxine"],
        "male_low": 0.8, "male_high": 1.8, "female_low": 0.8, "female_high": 1.8,
        "critical_low": 0.2, "critical_high": 7.0,
        "plain_low": "a low thyroid hormone level",
        "plain_high": "a high thyroid hormone level",
        "clinical_low": "Consistent with hypothyroidism",
        "clinical_high": "Consistent with hyperthyroidism/thyrotoxicosis",
    },
    "t3": {
        "display_name": "T3", "category": "Thyroid", "unit": "ng/dL",
        "aliases": ["total t3", "triiodothyronine"],
        "male_low": 80, "male_high": 200, "female_low": 80, "female_high": 200,
        "critical_low": 40, "critical_high": 400,
        "plain_low": "a low thyroid hormone level",
        "plain_high": "a high thyroid hormone level",
        "clinical_low": "Consider hypothyroidism or non-thyroidal illness",
        "clinical_high": "Consider thyrotoxicosis",
    },
    "t4": {
        "display_name": "T4", "category": "Thyroid", "unit": "ug/dL",
        "aliases": ["total t4", "thyroxine"],
        "male_low": 5.0, "male_high": 12.0, "female_low": 5.0, "female_high": 12.0,
        "critical_low": 2.0, "critical_high": 20.0,
        "plain_low": "a low thyroid hormone level",
        "plain_high": "a high thyroid hormone level",
        "clinical_low": "Consistent with hypothyroidism",
        "clinical_high": "Consistent with hyperthyroidism",
    },
    # -------------------------------------------------------------- Lipid --
    "total_cholesterol": {
        "display_name": "Total Cholesterol", "category": "Lipid", "unit": "mg/dL",
        "aliases": ["cholesterol", "tc", "cholesterol total"],
        "male_low": 0, "male_high": 200, "female_low": 0, "female_high": 200,
        "critical_low": 0, "critical_high": 400,
        "plain_low": "a low cholesterol level (usually not a concern)",
        "plain_high": "high cholesterol, which can raise heart disease risk",
        "clinical_low": "Not clinically significant",
        "clinical_high": "Hypercholesterolemia — assess cardiovascular risk and consider statin therapy",
    },
    "ldl": {
        "display_name": "LDL", "category": "Lipid", "unit": "mg/dL",
        "aliases": ["ldl cholesterol", "ldl-c", "low density lipoprotein"],
        "male_low": 0, "male_high": 100, "female_low": 0, "female_high": 100,
        "critical_low": 0, "critical_high": 300,
        "plain_low": "a low LDL ('bad cholesterol') level, which is favorable",
        "plain_high": "a high LDL ('bad cholesterol') level, which can raise heart disease risk",
        "clinical_low": "Not clinically significant",
        "clinical_high": "Elevated LDL — assess cardiovascular risk, consider lifestyle/statin therapy",
    },
    "hdl": {
        "display_name": "HDL", "category": "Lipid", "unit": "mg/dL",
        "aliases": ["hdl cholesterol", "hdl-c", "high density lipoprotein"],
        "male_low": 40, "male_high": 60, "female_low": 50, "female_high": 60,
        "critical_low": 15, "critical_high": 100,
        "plain_low": "a low HDL ('good cholesterol') level, which can raise heart disease risk",
        "plain_high": "a high HDL ('good cholesterol') level, which is generally favorable",
        "clinical_low": "Low HDL — cardiovascular risk factor, encourage lifestyle modification",
        "clinical_high": "Not clinically concerning",
    },
    "triglycerides": {
        "display_name": "Triglycerides", "category": "Lipid", "unit": "mg/dL",
        "aliases": ["tg", "trig"],
        "male_low": 0, "male_high": 150, "female_low": 0, "female_high": 150,
        "critical_low": 0, "critical_high": 1000,
        "plain_low": "a low triglyceride level (usually not a concern)",
        "plain_high": "high triglycerides, which can raise heart and pancreas-related risks",
        "clinical_low": "Not clinically significant",
        "clinical_high": "Hypertriglyceridemia — assess pancreatitis risk if markedly elevated",
    },
    "vldl": {
        "display_name": "VLDL", "category": "Lipid", "unit": "mg/dL",
        "aliases": ["vldl cholesterol", "very low density lipoprotein"],
        "male_low": 2, "male_high": 30, "female_low": 2, "female_high": 30,
        "critical_low": 0, "critical_high": 100,
        "plain_low": "a low VLDL level (usually not a concern)",
        "plain_high": "a high VLDL level, related to triglyceride levels",
        "clinical_low": "Not clinically significant",
        "clinical_high": "Correlate with triglycerides; consider dyslipidemia management",
    },
    # ------------------------------------------------------------ Glucose --
    "fasting_glucose": {
        "display_name": "Fasting Glucose", "category": "Glucose", "unit": "mg/dL",
        "aliases": ["fbs", "fasting blood sugar", "glucose fasting"],
        "male_low": 70, "male_high": 100, "female_low": 70, "female_high": 100,
        "critical_low": 40, "critical_high": 400,
        "plain_low": "low blood sugar, which can cause shakiness or confusion",
        "plain_high": "high blood sugar, which may indicate prediabetes or diabetes",
        "clinical_low": "Hypoglycemia — evaluate cause and correct promptly",
        "clinical_high": "Hyperglycemia — assess for diabetes/prediabetes with HbA1c",
    },
    "hba1c": {
        "display_name": "HbA1c", "category": "Glucose", "unit": "%",
        "aliases": ["glycated hemoglobin", "glycosylated hemoglobin", "a1c"],
        "male_low": 4.0, "male_high": 5.6, "female_low": 4.0, "female_high": 5.6,
        "critical_low": 2.0, "critical_high": 14.0,
        "plain_low": "a lower-than-normal average blood sugar level",
        "plain_high": "a higher-than-normal average blood sugar level over the past 2-3 months",
        "clinical_low": "Consider hypoglycemic episodes or hemolytic conditions affecting the assay",
        "clinical_high": "Poor glycemic control — reassess diabetes management, consider medication adjustment",
    },
    "random_glucose": {
        "display_name": "Random Glucose", "category": "Glucose", "unit": "mg/dL",
        "aliases": ["rbs", "random blood sugar", "glucose random"],
        "male_low": 70, "male_high": 140, "female_low": 70, "female_high": 140,
        "critical_low": 40, "critical_high": 400,
        "plain_low": "low blood sugar, which can cause shakiness or confusion",
        "plain_high": "high blood sugar",
        "clinical_low": "Hypoglycemia — evaluate cause and correct promptly",
        "clinical_high": "Hyperglycemia — assess glycemic control",
    },
    "post_prandial_glucose": {
        "display_name": "Post-Prandial Glucose", "category": "Glucose", "unit": "mg/dL",
        "aliases": ["ppbs", "pp glucose", "postprandial glucose", "2hr pp glucose"],
        "male_low": 70, "male_high": 140, "female_low": 70, "female_high": 140,
        "critical_low": 40, "critical_high": 400,
        "plain_low": "low blood sugar after eating",
        "plain_high": "high blood sugar after eating",
        "clinical_low": "Hypoglycemia — evaluate cause and correct promptly",
        "clinical_high": "Postprandial hyperglycemia — assess glycemic control",
    },
    # -------------------------------------------------------------- Other --
    "crp": {
        "display_name": "CRP", "category": "Other", "unit": "mg/L",
        "aliases": ["c-reactive protein", "c reactive protein"],
        "male_low": 0.0, "male_high": 10.0, "female_low": 0.0, "female_high": 10.0,
        "critical_low": 0.0, "critical_high": 350.0,
        "plain_low": "a low inflammation marker (usually not a concern)",
        "plain_high": "an elevated inflammation marker, often seen with infection or inflammation",
        "clinical_low": "Not clinically significant",
        "clinical_high": "Elevated inflammatory marker — correlate with clinical picture for infection/inflammation",
    },
    "esr": {
        "display_name": "ESR", "category": "Other", "unit": "mm/hr",
        "aliases": ["erythrocyte sedimentation rate", "sed rate"],
        "male_low": 0, "male_high": 15, "female_low": 0, "female_high": 20,
        "critical_low": 0, "critical_high": 100,
        "plain_low": "a low inflammation marker (usually not a concern)",
        "plain_high": "an elevated inflammation marker",
        "clinical_low": "Not clinically significant",
        "clinical_high": "Nonspecific marker of inflammation — correlate clinically with CRP",
    },
    "ferritin": {
        "display_name": "Ferritin", "category": "Other", "unit": "ng/mL",
        "aliases": ["s.ferritin", "serum ferritin"],
        "male_low": 24, "male_high": 336, "female_low": 11, "female_high": 307,
        "critical_low": 5, "critical_high": 1000,
        "plain_low": "low iron stores in your body",
        "plain_high": "high iron stores, or an active inflammation marker",
        "clinical_low": "Suggests iron deficiency",
        "clinical_high": "Consider iron overload, inflammation, or hepatocellular release",
    },
    "vitamin_d": {
        "display_name": "Vitamin D", "category": "Other", "unit": "ng/mL",
        "aliases": ["25-oh vitamin d", "25(oh)d", "vit d", "vitamin d3"],
        "male_low": 30, "male_high": 100, "female_low": 30, "female_high": 100,
        "critical_low": 5, "critical_high": 150,
        "plain_low": "low vitamin D, which can affect bone and muscle health",
        "plain_high": "high vitamin D, usually from excess supplementation",
        "clinical_low": "Vitamin D deficiency — consider supplementation",
        "clinical_high": "Vitamin D toxicity — assess for hypercalcemia and review supplement dosing",
    },
    "vitamin_b12": {
        "display_name": "Vitamin B12", "category": "Other", "unit": "pg/mL",
        "aliases": ["b12", "vit b12", "cobalamin"],
        "male_low": 200, "male_high": 900, "female_low": 200, "female_high": 900,
        "critical_low": 100, "critical_high": 2000,
        "plain_low": "low vitamin B12, which can cause fatigue or nerve symptoms",
        "plain_high": "high vitamin B12, usually from supplementation",
        "clinical_low": "B12 deficiency — consider pernicious anemia, malabsorption, dietary cause",
        "clinical_high": "Usually reflects supplementation; rarely clinically significant",
    },
    "calcium": {
        "display_name": "Calcium", "category": "Other", "unit": "mg/dL",
        "aliases": ["ca", "s.calcium", "serum calcium"],
        "male_low": 8.5, "male_high": 10.5, "female_low": 8.5, "female_high": 10.5,
        "critical_low": 6.0, "critical_high": 13.0,
        "plain_low": "low blood calcium, which can cause muscle cramps or tingling",
        "plain_high": "high blood calcium, which can cause fatigue or confusion",
        "clinical_low": "Hypocalcemia — check albumin-corrected calcium, PTH, vitamin D",
        "clinical_high": "Hypercalcemia — consider hyperparathyroidism or malignancy",
    },
    "magnesium": {
        "display_name": "Magnesium", "category": "Other", "unit": "mg/dL",
        "aliases": ["s.magnesium", "serum magnesium"],
        "male_low": 1.7, "male_high": 2.2, "female_low": 1.7, "female_high": 2.2,
        "critical_low": 1.0, "critical_high": 4.0,
        "plain_low": "low magnesium, which can affect muscle and heart function",
        "plain_high": "high magnesium, which can affect muscle and heart function",
        "clinical_low": "Hypomagnesemia — cardiac monitoring advised if severe",
        "clinical_high": "Hypermagnesemia — often seen in renal impairment; cardiac monitoring advised",
    },
}


def _build_alias_map() -> dict[str, str]:
    alias_map: dict[str, str] = {}
    for key, entry in REFERENCE_RANGES.items():
        alias_map[key] = key
        alias_map[key.replace("_", " ")] = key
        alias_map[entry["display_name"].strip().lower()] = key
        for alias in entry.get("aliases", []):
            alias_map[alias.strip().lower()] = key
    return alias_map


ALIAS_MAP: dict[str, str] = _build_alias_map()


def normalize_test_name(raw_name: str) -> Optional[str]:
    """Map free-text test name (from OCR) to a canonical reference-ranges key."""
    return ALIAS_MAP.get(raw_name.strip().lower())


def resolve_range(canonical_key: str, gender: str = "unknown") -> dict:
    """Resolve gender-appropriate normal range plus critical thresholds and unit."""
    entry = REFERENCE_RANGES[canonical_key]
    gender_norm = (gender or "unknown").strip().lower()
    if gender_norm in ("male", "m"):
        low, high = entry["male_low"], entry["male_high"]
    elif gender_norm in ("female", "f"):
        low, high = entry["female_low"], entry["female_high"]
    else:
        low = min(entry["male_low"], entry["female_low"])
        high = max(entry["male_high"], entry["female_high"])
    return {
        "low": float(low),
        "high": float(high),
        "critical_low": float(entry["critical_low"]),
        "critical_high": float(entry["critical_high"]),
        "unit": entry["unit"],
    }
